spring:
  application:
    name: GooInProPartTimerAPI
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:13307/gooinprodb
    username: gooinprodbuser
    password: gooinprodbuser
  data:
    mongodb:
      uri: mongodb://gooinprochatdbuser:gooinprochatdbuser@localhost:27017/gooinprochatdb?authSource=gooinprochatdb

    hikari:
      minimum-idle: 2
      maximum-pool-size: 5
      connection-timeout: 5000

  devtools:
    livereload:
      enabled: true
  freemarker:
    cache: false

  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MariaDB103Dialect
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        # Time zone 설정
        jdbc.time_zone: UTC  # DB에서 데이터를 UTC로 처리
        hibernate.jdbc.time_zone: UTC
        spring.jpa.properties.hibernate.jdbc.time_zone: UTC

org:
  gooinpro:
    accessTime: 100
    refreshTime: 10000
    alwaysNew: true

naver:
  map:
    api:
      client-id: ${NAVER_MAP_API_CLIENT_ID}
      client-secret: ${NAVER_MAP_API_CLIENT_SECRET}
      url: ${NAVER_MAP_API_URL}